# Generated by Django 4.0.6 on 2022-10-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountregister',
            name='email',
            field=models.EmailField(default=None, max_length=150),
        ),
    ]
