# Generated by Django 4.0.6 on 2022-10-20 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_accountregister_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountregister',
            name='email',
        ),
    ]
