# Generated by Django 4.0.6 on 2022-10-12 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('password_confirm', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('aadhar', models.FileField(upload_to='uploads/')),
                ('photo', models.ImageField(upload_to='image')),
                ('Account', models.CharField(choices=[('SA', 'saving Account'), ('CA', 'current Account')], max_length=20)),
                ('emply_num', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
