# Generated by Django 4.0.6 on 2022-10-13 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_delete_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='aadhar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='photo',
        ),
    ]
