# Generated by Django 4.0.6 on 2022-10-13 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_aadhar_remove_user_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Account',
        ),
        migrations.RemoveField(
            model_name='user',
            name='emply_num',
        ),
    ]
