# Generated by Django 4.0.6 on 2022-10-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_aadhar_user_emply_num_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('password_confirm', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('emply_num', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/')),
                ('aadhar', models.FileField(upload_to='aadhar/')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
