# Generated by Django 4.0.6 on 2022-10-18 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='emply_num',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
